version: '3' 
services:  
  app:
    # 1.Repository URI for our app image
    image: XXXXXXXXXX.dkr.ecr.eu-west-1.amazonaws.com/ror-ecs-app    
    build:      
      context: .
      dockerfile: ./docker/app/Dockerfile    
  web:
    # 2.Repository URI for our web image
    image: XXXXXXXXXX.dkr.ecr.eu-west-1.amazonaws.com/ror-ecs-web
    build:      
      context: .
      dockerfile: ./docker/web/Dockerfile    
    links:      
      - app    
    ports:      
      - 80:80